### ISSUE TITLE
Text boxes overflow after font change

### ISSUE THREAD

**Issue by therandomcode** [helpscout/figma-wirebox#5]
Could you add an option to keep the fonts (or set our own font instead of Roboto) to prevent text boxes from overflowing? (See attached image.) 
![image](https://user-images.githubusercontent.com/10263722/101771253-eba23800-3ae9-11eb-98b7-0738ea83ad6b.png)

Fab plugin otherwise. Cheers.

**Comment by seanehalpin** [comment]
Sorry for the _very_ late update 😅 

This is a tricky one, as plugins load fonts async, and font availability is per client, that enforcing one font (Roboto) was just the more pragmatic choice. Issues arise when the sizing of the font is very different to Roboto, unfortunately.

I'm going to punt this for now but open to any suggestions on how it can be improved.
